services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_ai_backend
    restart: unless-stopped
    ports:
      - "5678:5678" # Mapea el puerto 5678 del contenedor al puerto 5678 del host
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Santiago
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
